version: 2.1
orbs:
  slack: circleci/slack@3.4.2

jobs:
  build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:stitch-tap-tester
    steps:
      - checkout
      - run:
          name: 'Setup virtual env'
          command: |
            aws s3 cp s3://com-stitchdata-dev-deployment-assets/environments/tap-tester/tap_tester_sandbox dev_env.sh
            python3 -mvenv /usr/local/share/virtualenvs/tap-zendesk-chat
            source /usr/local/share/virtualenvs/tap-zendesk-chat/bin/activate
            pip install -U 'pip<19.2' 'setuptools<51.0.0'
            pip install .[dev]
      - run:
          name: 'pylint'
          command: |
            source dev_env.sh
            source /usr/local/share/virtualenvs/tap-zendesk-chat/bin/activate
            pylint tap_zendesk_chat -d "$PYLINT_DISABLE_LIST,no-self-use"
      - run:
          name: 'JSON Validator'
          command: |
            source /usr/local/share/virtualenvs/tap-tester/bin/activate
            stitch-validate-json tap_zendesk_chat/schemas/*.json
      - run:
          name: 'Unit Tests'
          command: |
            source /usr/local/share/virtualenvs/tap-zendesk-chat/bin/activate
            pip install coverage
            nosetests --with-coverage --cover-erase --cover-package=tap_zendesk_chat --cover-html-dir=htmlcov tests/unittests
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: htmlcov
      - run:
          name: 'Integration Tests'
          command: |
            source dev_env.sh
            source /usr/local/share/virtualenvs/tap-tester/bin/activate
            run-test --tap=tap-zendesk-chat tests
      - slack/status:
          channel: 'stitch-tap-tester-tests'
          mentions: "${CIRCLE_USERNAME}"
          fail_only: true
          only_for_branches: master
          failure_message: |
            :red_circle: ${CIRCLE_JOB} failed!

workflows:
  version: 2
  commit: &commit_jobs
    jobs:
      - build:
          context:
            - circleci-user
            - tap-tester-user

  build_daily:
    <<: *commit_jobs
    triggers:
      - schedule:
          cron: "0 14 * * *"
          filters:
            branches:
              only:
                - master
